apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: uRe
    labels:
      app: openshift-letsencrypt
    name: openshift-letsencrypt
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-letsencrypt:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/ure/openshift-letsencrypt.git
      type: Git
    strategy:
      type: Docker
  status:
    lastVersion: 0
kind: List
metadata: {}
